org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=256m -XX:+UseParallelGC -XX:ReservedCodeCacheSize=64m
org.gradle.parallel=false
org.gradle.vfs.watch=false
org.gradle.workers.max=2
kotlin.daemon.jvmargs=-Xmx256m
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

